[package]
name = "plushy-plushes"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
path = "mod.rs"

[dependencies]
plushy-traits = { path = "../traits", version = "0.0.1" }